name: Build Debian Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential file
          sudo apt-get install -y libspdlog-dev nlohmann-json3-dev libcurl4-openssl-dev libargparse-dev

      - name: Configure with CMake
        run: cmake --preset linux-native -B build

      - name: Build package
        run: |
          cd build
          make package -j $(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: d2hs-package
          path: build/*.deb
